### ISSUE TITLE
How do i implement Custom keyword Auto completion

### ISSUE THREAD

**Issue by kashif-ali-khan** [acrodata/code-editor#1]
Hi team,
I am going through This package (code-editor),
Basic things are working fine,

I want to know, how can i implement
Custom key word autocompletion
and
custom Text highlight (different color (style) for different keyword)
using this plugin

**Comment by nzbin** [comment]
For CodeMirror 6, all the feature can be implemented with extensions. You can check the online examples https://codemirror.net/try/?example=Custom%20completions

With code-editor, you should just implement the extensions for your demand.

```html
<code-editor [extensions]="extensions" />
```

```ts
extensions = [
  autocompletion({override: [myCompletions]}),
  ...
];
```

**Comment by kashif-ali-khan** [comment]
Thanks @nzbin .
This really helps
