### ISSUE TITLE
Ability to make the diff editor readonly

### ISSUE THREAD

**Issue by gerbsen** [acrodata/code-editor#2]
hey there! the project here is absolutely awesome. I would really like to use it for my project. There is only one little issue. Is there any way to make the DiffEditor `readOnly`? I looked at the code, but couldn't figure out what to do. :(

**Comment by nzbin** [comment]
For CodeMirror 6, all features can be implemented with extensions.  https://github.com/acrodata/code-editor/issues/1#issuecomment-2172475058

```ts
import { EditorState } from '@codemirror/state';
import { EditorView } from '@codemirror/view';

extensions = [
  EditorState.readOnly.of(true),
  // or 
  // EditorView.editable.of(false)
];
```

```html
<diff-editor [originalExtensions]="extensions"
             [modifiedExtensions]="extensions" />
```
